resources:
  - name: myCluster
    type: cluster
    integration: MyAwsSoftSrvKeys
    versionTemplate
      sourceName: default
      region: us-east-1
  - name: myImage
    type: image
    versionTemplate:
      sourceName: trriplejay/simpleserver
      versionName: master
  - name: myScaling
    type: replicas
    versionTemplate:
      count: 2
      minReplicas: 1
      maxReplicas: 5
      autoScalingRole: ecsAutoscaleRole
      autoScalingPolicies:
        - PolicyName: UpPolicy
          PolicyType: StepScaling
          StepScalingPolicyConfiguration:
            AdjustmentType: ChangeInCapacity
            Cooldown: 300
            MetricAggregationType: Average
            StepAdjustments:
            - MetricIntervalLowerBound: 0
              MetricIntervalUpperBound: 20
              ScalingAdjustment: 1
            - MetricIntervalLowerBound: 20
              ScalingAdjustment: 2
        - PolicyName: DownPolicy
          PolicyType: StepScaling
          StepScalingPolicyConfiguration:
            AdjustmentType: ChangeInCapacity
            Cooldown: 300
            MetricAggregationType: Average
            StepAdjustments:
            - MetricIntervalUpperBound: 0
              MetricIntervalLowerBound: -10
              ScalingAdjustment: -1
            - MetricIntervalUpperBound: -10
              ScalingAdjustment: -2
      metricAlarms:
        - AlarmName: UpAlarm
        - AlarmDescription: "test scaleup"
          ComparisonOperator: GreaterThanOrEqualToThreshold
          EvaluationPeriods: 1
          MetricName: MemoryUtilization
          Namespace: AWS/ECS
          Statistic: Average
          Period: 60
          Threshold: 70
          AlarmActions:
          - UpPolicy
        - AlarmName: DownAlarm
          AlarmDescription: "test scaledown"
          ComparisonOperator: LessThanOrEqualToThreshold
          EvaluationPeriods: 1
          MetricName: MemoryUtilization
          Namespace: AWS/ECS
          Statistic: Average
          Period: 60
          Threshold: 30
          AlarmActions:
          - DownPolicy
jobs:

  - name: myManifest
    type: manifest
    steps:
      - IN: myImage
      - IN: myScaling

  - name: myDeploy
    type: deploy
    deployMethod: upgrade
    steps:
      - IN: myManifest
      - IN: myCluster