use-shipctl-master: &masterShipctl
  - pushd /tmp
  - git clone https://github.com/trriplejay/node.git
  - ./node/shipctl/$SHIPPABLE_NODE_ARCHITECTURE/$SHIPPABLE_NODE_OPERATING_SYSTEM/install.sh
  - popd


resources:

  - name: test-jira-win
    type: notification
    integration: test-jira-account-based

jobs:


  - name: win-testJira
    type: runSh
    runtime:
      nodePool: w16-byon
    steps:
      - IN: test-jira-win
      - TASK:
          script:
            # - *masterShipctl

            - shipctl notify test-jira-win  -type "Bug" -description "WIN failure in $env:BUILD_NUMBER" -summary "WINDOWS something went wrong"
              # no type
            # - shipctl notify test-jira-win -project-id MYAP  --description="failure in $BUILD_NUMBER" --summary="something went wrong" || true
            #   # no summary
            # - shipctl notify test-jira-win --project-id MYAP --type=Bug --description="failure in $BUILD_NUMBER" || true
            #   # no description
            # - shipctl notify test-jira-win --project-id=MYAP --type=Bug --summary="something went wrong" || true
            # # success scenarios
            # - shipctl notify test-jira-win --project-id=MYAP --type=Bug --description="failure in $BUILD_NUMBER" --summary="something went wrong"
            # - shipctl notify test-jira-win --project-id=MYAP --type=Story --description="once upon a time, in a build called $BUILD_NUMBER" --summary="this is my story"
            # - shipctl notify test-jira-win --project-id=MYAP --type=Bug --description="see attachment $BUILD_NUMBER" --summary="something went wrong. see attachment" --attach-file=message.json
