
resources:
  - name: winParamsA
    type: params
    versionTemplate:
      params:
        paramsA_foo: bar
        paramsA_hello: world

jobs:
  - name: windowsSetup
    type: runSh
    runtime:
      nodePool: w16-byon
    steps:
      - IN: sample_pipelines_windowsReplicate_rSync
      - OUT: winParamsA
        overwrite: true
      - TASK:
          script:
            - shipctl put_resource_state winParamsA "paramsA_foo" "bar"
            - shipctl put_resource_state winParamsA "paramsA_hello" "world"

  
