# Language setting
language: python

# Version number
python:
  - 2.7

build:
  ci:
    - python --version
    - echo "hello"


jobs:
  - name: firstJob-repro
    type: runSh
    dependencyMode: strict
    flags:
      - repro
    steps:
      - IN: myRepo-repro
      - OUT: sample_pipelines_ciRepo
        replicate: myRepo-repro

resources:
  - name: myRepo-repro
    type: gitRepo
    flags:
      - repro
    integration: "github"
    pointer:
      sourceName: trriplejay/sample_pipelines
      branch: master
