jobs:
  - name: simple-mani-mani2mani
    type: manifest
    flags:
      - mani2mani
    steps:
      - IN: stagingTrigger-mani2mani
      - IN: simple-params-mani2mani
      - IN: simple-image-mani2mani
      - IN: simple-opts-mani2mani



  - name: combined-manifest-mani2mani
    type: manifest
    flags:
      - mani2mani
    steps:
      # - IN: nginx-image-mani2mani
      - IN: busybox-image-mani2mani
      - IN: simple-mani-mani2mani
      - IN: simpleReplicas-mani2mani
      - IN: base-options-mani2mani

  - name: combined-mani-print
    type: runSh
    steps:
      - IN: combined-manifest-mani2mani
      - TASK:
        - script: cat $COMBINEDMANIFESTMANI2MANI_STATE/manifests.json | jq '.'

  # - name: combined-mani2mani
  #   type: deploy
  #   flags:
  #     - mani2mani
  #   steps:
  #     - IN: combined-manifest-mani2mani
  #     - IN: simple-opts-mani2mani
  #       applyTo:
  #         - simple-image-mani2mani
  #     - IN: ecsProduction-mani2mani
  #     - TASK: managed
  #       deployMethod: replace
