
test-state-A: &testA
  - echo "testing stateA"
  - ls -latr $(shipctl get_resource_state stateA)
  - cat $JOB_STATE/stateA.env || echo "no env file found"
  - ls -latr $(shipctl get_resource_meta stateA)
  - cat $(shipctl get_resource_meta stateA)/version.json | jq '.' || echo "no versionjson file found"
  - echo "hello world" > test.txt
  - shipctl copy_file_to_resource_state test.txt stateA
  - shipctl copy_file_to_state text.txt
  - ls -latr $(shipctl get_resource_state stateA)
  - ls -latr $(shipctl get_resource_meta stateA)
  - cat $(shipctl get_resource_meta stateA)/version.json | jq '.' || echo "no versionjson file found"
  - ls -latr $JOB_PREVIOUS_STATE

test-state-B: &testB
  - echo "testing stateB"
  - ls -latr $(shipctl get_resource_state stateB)
  - cat $(shipctl get_resource_state stateB) stateB.env || echo "no env file found"
  - cat $JOB_STATE/stateB.env || echo "no env file found"
  - shipctl put_resource_state stateB versionName "$BUILD_NUMBER"
  - cat $JOB_STATE/stateB.env || echo "no env file found"


resources:
  - name: stateA
    type: state
  - name: stateB
    type: state


jobs:
  - name: testState1
    type: runSh
    steps:
      - IN: stateA
        switch: off
      - OUT: stateA
      - OUT: stateB
      - TASK:
          script:
            - *testA
            - *testB

  - name: testState2
    dependencyMode: strict
    type: runSh
    steps:
      - IN: stateB
      - IN: stateA
      - TASK:
          script:
            - *testA
            - *testB