use-shipctl-master: &masterShipctl
  - pushd /tmp
  - git clone https://github.com/trriplejay/node.git
  - ./node/shipctl/$SHIPPABLE_NODE_ARCHITECTURE/$SHIPPABLE_NODE_OPERATING_SYSTEM/install.sh
  - popd


resources:
  - name: stateA
    type: state

  - name: stateB
    type: state

  - name: stateRepo
    type: gitRepo
    integration: github
    versionTemplate:
      branch: state
      sourceName: trriplejay/sample_pipelines

  - name: stateRepo2
    type: gitRepo
    integration: github
    versionTemplate:
      branch: master
      sourceName: trriplejay/simpleserver

  - name: outRepo
    type: gitRepo
    integration: github
    versionTemplate:
      branch: master
      sourceName: trriplejay/sample_pipelines
      buildOnCommit: false

  - name: paramsA
    type: params
    versionTemplate:
      params:
        paramsA_foo: bar
        paramsA_hello: world

  - name: paramsB
    type: params
    versionTemplate:
      params:
        btest: true

  - name: replicasB
    type: replicas
    versionTemplate:
      count: 1

- name: badA
    type: file
    versionTemplate:
      versionName: "testA"

- name: badB
    type: file
    versionTemplate:
      versionName: "testB"

jobs:
  - name: jobA
    type: runSh
    steps:
      - TASK:
          script:
            - echo " hi" > jobA.txt
            - shipctl put_resource_state $JOB_NAME versionName $BUILD_NUMBER
            - shipctl put_resource_state $JOB_NAME jobAFoo jobABar
            - shipctl copy_file_to_state jobA.txt
  - name: jobB
    type: runSh
    steps:
      - TASK:
          script:
            - echo " bye"

  - name: setupJob
    type: runSh
    runtime:
      nodePool: u16-dyna
    steps:
      - IN: sample_pipelines_state_rSync
      - TASK:
          name: set-up-A
          script:
            - shipctl put_resource_state stateA foo bar
            - if [ -n "$CUSTOM" ]; then shipctl put_resource_state stateA custom "$CUSTOM"; fi
            - echo "testing 1..2..3" > test.txt
            - shipctl copy_file_to_resource_state test.txt stateA
      - TASK:
          name: set-up-B
          script:
            - shipctl put_resource_state stateB test value
            - if [ -n "$CUSTOM" ]; then shipctl put_resource_state stateB custom "$CUSTOM"; fi
      - OUT: stateA
        overwrite: true
      - OUT: stateB
        overwrite: true

  - name: testStateJobs
    type: runSh
    steps:
      - IN: setupJob
      - IN: jobA
        switch: off
      - TASK:
          script:
            - *masterShipctl
            - shipctl replicate jobA $JOB_NAME

  - name: testStateErrors
    type: runSh
    steps:
      - IN: setupJob
      - IN: badA
        switch: off
      - OUT: outRepo
      - OUT: badB
      - IN: stateRepo
        switch: off
      - OUT: replicasB
      - IN: simpleserver_windowsNotifications
        switch: off
      - OUT: shippable_java_test_ciRepo #must be added to pipeline separately
      - TASK:
          script:
            - *masterShipctl
            ######### Error checking
            - shipctl replicate paramsA outRepo || true  # same type if non-repo
            - shipctl replicate stateRepo paramsB || true
            - shipctl replicate stateRepo shippable_java_test_ciRepo || true
            - shipctl replicate paramsA replicasB || true
            - shipctl replicate $JOB_NAME $JOB_NAME || true
            - shipctl replicate $JOB_NAME outRepo || true
            - shipctl replicate simpleserver_windowsNotifications outRepo || true
            ######### Warnings
            - shipctl replicate badA badB --bad --notvalid #warning only

  - name: testStateState
    type: runSh
    steps:
      - IN: setupJob

      - IN: stateA
        switch: off
      - IN: jobA
        switch: off
      - OUT: stateA
      - OUT: stateB

      - TASK:
          script:
            - *masterShipctl
            # - sudo apt-get update # ubuntu
            - sudo apt-get install -y tree # ubuntu
            # - yum install -y tree # centos
            # - alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'" # macos


            ## stateA stuff
            # - cat $JOB_PATH/IN/stateA/version.json
            # - tree $JOB_PATH/IN/stateA/state #because it is IN and OUT
            # - shipctl replicate stateA stateA --metadata-only
            # - tree $STATEA_STATE
            ## stateB stuff
            - cat $JOB_PATH/OUT/stateB/version.json | jq '.version.propertyBag'
            - tree $STATEB_STATE
            - shipctl replicate stateA stateB
            - tree $STATEB_STATE
            - cat $JOB_PATH/OUT/stateB/version.json | jq '.version.propertyBag'

  - name: testStateParams
    type: runSh
    steps:
      - IN: setupJob
      - IN: paramsA
      - OUT: paramsB
      - TASK:
          script:
            - *masterShipctl
            - shipctl replicate paramsA paramsB

  - name: testStateRepo
    type: runSh
    steps:
      - IN: setupJob
      - IN: stateRepo
        switch: off
      - OUT: stateRepo2
      - TASK:
          script:
            - *masterShipctl
            - shipctl replicate stateRepo stateRepo2

  - name: testStateFinal
    dependencyMode: strict
    type: runSh
    steps:
      - IN: stateB
      - IN: stateA
      - IN: paramsA
        switch: off
      - IN: paramsB
        switch: off
      - IN: outRepo
        switch: off
      - IN: stateRepo2
        switch: off
      - IN: testState1

      # - TASK:
      #     name: stateA-details
      #     script:
      #       - echo "------------------ file list"
      #       - ls -latr $(shipctl get_resource_state stateA)
      #       - echo "------------------ version contents"
      #       - cat $(shipctl get_resource_meta stateA)/version.json | jq '.version'
      # - TASK:
      #     name: stateB-details
      #     script:
      #       - echo "------------------ file list"
      #       - ls -latr $(shipctl get_resource_state stateB)
      #       - echo "------------------ version contents"
      #       - cat $(shipctl get_resource_meta stateB)/version.json | jq '.version'
      - TASK:
          name: paramsB-details
          script:
            - cat $(shipctl get_resource_meta paramsB)/version.json | jq '.version.propertyBag'
            - printenv
      - TASK:
          name: gitRepo-details
          script:
            - cat $(shipctl get_resource_meta outRepo)/version.json | jq '.version.propertyBag'
