jobs:
  - name: simple-mani-serialCheck
    type: manifest
    flags:
      - serialCheck
    steps:
      - IN: stagingTrigger-serialCheck
      - IN: simple-params-serialCheck
      - IN: simple-image-serialCheck
      - IN: simple-opts-serialCheck

  - name: nginx-mani-serialCheck
    type: manifest
    flags:
      - serialCheck
    steps:
      - IN: stagingTrigger-serialCheck
      - IN: nginx-image-serialCheck
      - IN: nginx-params-serialCheck
      - IN: nginx-opts-serialCheck

  - name: runSh1-serialCheck
    type: runSh
    flags:
      - serialCheck
      - jtFlow
    steps:
      - TASK:
        - script: pwd
        - script: sleep 30

  - name: runSh2-serialCheck
    type: runSh
    flags:
      - serialCheck
      - jtFlow
    steps:
      - TASK:
        - script: pwd
        - script: sleep 30


  - name: runSh3-serialCheck
    type: runSh
    flags:
      - serialCheck
      - jtFlow
    steps:
      - IN: runSh1-serialCheck
      - IN: runSh2-serialCheck
      - TASK:
        - script: pwd
        - script: sleep 30
