
test-state-A: &testA
  - echo "testing stateA"
  - ls -latr $(shipctl get_resource_state stateA)
  - cat $(shipctl get_resource_state stateA) stateA.env || echo "no env file found"

test-state-B: &testB
  - echo "testing stateB"
  - ls -latr $(shipctl get_resource_state stateB)
  - cat $(shipctl get_resource_state stateB) stateB.env || echo "no env file found"


resources:
  - name: stateA
    type: state
  - name: stateB
    type: state


jobs:
  - name: testState1
    type: runSh
    steps:
      - IN: stateA
        switch: off
      - OUT: stateA
      - OUT: stateB
      - TASK:
          script:
            - *testA
            - *testB

  - name: testState2
    dependencyMode: strict
    type: runSh
    steps:
      - IN: stateB
      - IN: stateA
      - TASK:
          script:
            - *testA
            - *testB