use-shipctl-master: &masterShipctl
  - pushd /tmp
  - git clone https://github.com/trriplejay/node.git
  - ./node/shipctl/$SHIPPABLE_NODE_ARCHITECTURE/$SHIPPABLE_NODE_OPERATING_SYSTEM/install.sh
  - popd


resources:

  - name: test-jira-res
    type: notification
    integration: test-jira-account-based

jobs:


  - name: win-testJira
    type: runSh
    runtime:
      nodePool: w16-byon
    steps:
      - IN: test-jira-res
      - TASK:
          script:
            # - *masterShipctl
            - shipctl replicate win-repoMatchSource win-repoMatchTarget -match_settings
            # - shipctl replicate inparams win-repoMatchTarget -match_settings
