resources:

  - name: badRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/badrepo

jobs:

  - name: badRun
    type: runSh
    steps:
      script:
        - echo "hello world"
    on_success:
      - script:
        - >-
          COMMENT="This is a multi-line
          comment, isn't that great?"
        - 'this line has a : in it. i hope it works!'
        - echo $COMMENT
