use-shipctl-master: &masterShipctl
  - pushd /tmp
  - git clone https://github.com/trriplejay/node.git
  - ./node/shipctl/$SHIPPABLE_NODE_ARCHITECTURE/$SHIPPABLE_NODE_OPERATING_SYSTEM/install.sh
  - popd


resources:


  - name: repoMatchSource
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/simpleserver
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnComment: test.*
      buildOnTagPush: true
      buildOnRelease: true

  - name: repoMatchTarget
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/simpleserver
      tags:
        only:
          - v0.*
          - v1.*
          - v2.*
      #   except:
      #     - v0.*-test
      #     - v1.*-test
      #     - v2.*-test
      branches:
        only:
          - master
          - dev*
        except:
          - dev-test
      buildOnCommit: false
      buildOnPullRequest: true

jobs:


  - name: testStateMatching
    type: runSh
    steps:
      # - IN: setupJob
      - IN: repoMatchSource
      - OUT: repoMatchTarget
      - TASK:
          script:
            # - *masterShipctl
            - shipctl replicate repoMatchSource repoMatchTarget --match-settings
