jobs:
  - name: deployChanges
    type: runSh
    dependencyMode: strict
    steps:
      - IN: myRepo
      - TASK:
        - script: echo "hello world"
        - script: echo "-------- state variables from CI --------------"
        - script: cat $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: echo "---------------------------------------------"
        - script: source $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: ciBuildNumber=$(shipctl get_resource_version_name simpleserver_runCI)
        - script: echo "ci build number was $ciBuildNumber"
        - script: echo "myRepo versionName is- $MYREPO_VERSIONNAME"
        - script: jq . /build/message.json

  - name: simpleserver_runCI
    type: runCI
    steps:
      - OUT: myRepo
        replicate: simpleserver_ciRepo
