jobs:
  - name: deployChanges
    type: runSh
    steps:
      - IN: simpleserver_runCI
      - TASK:
        - script: echo "hello world"
        - script: cat $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: source $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: ciBuildNumber=$(shipctl get_resource_version_name simpleserver_runCI)
        - script: echo "ci build number was $ciBuildNumber"
        - script: echo "ci build commit sha was $ciCommit"
        - script: echo "ci branch was $ciBranch"
