jobs:
  - name: simple-mani-deploy
    type: manifest
    flags:
      - deploy
    steps:
      - IN: stagingTrigger-deploy
      - IN: simple-params-deploy
      - IN: simple-image-deploy
      # - IN: simple-opts-deploy

  - name: nginx-mani-deploy
    type: manifest
    flags:
      - deploy
    steps:
      - IN: stagingTrigger-deploy
      - IN: nginx-image-deploy
      - IN: nginx-params-deploy
      - IN: nginx-opts-deploy

  - name: staging-deploy-A-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: simple-mani-deploy
      # - IN: nginx-mani-deploy
      - IN: ecsStaging-deploy

  - name: staging-deploy-B1-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: simple-mani-deploy
      - IN: nginx-mani-deploy
      - IN: ecsStaging-deploy
      - TASK: managed
        deployMethod: blueGreen

  - name: staging-deploy-B2-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: nginx-mani-deploy
      - IN: ecsStaging-deploy
      - IN: simpleReplicas-deploy
      - TASK: managed
        deployMethod: replace

  - name: prod-deploy-A-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: staging-deploy-A-deploy
        switch: off
      - IN: ecsProduction-deploy

  - name: prod-deploy-B-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: staging-deploy-B1-deploy
        switch: off
      - IN: staging-deploy-B2-deploy
        switch: off
      - IN: ecsProduction-deploy

  - name: combined-manifest-deploy
    type: manifest
    flags:
      - deploy
    steps:
      # - IN: nginx-image-deploy
#      - IN: timed-deployment-deploy
      - IN: busybox-image-deploy
      - IN: simple-image-deploy
      - IN: simpleReplicas-deploy
      - IN: base-options-deploy

  - name: combined-deploy
    type: deploy
    method: upgrade
    stabilityDuration: 20
    workflow: parallel
    flags:
      - deploy
    steps:
      - IN: combined-manifest-deploy
        force: true
      # - IN: simple-opts-deploy
      #   applyTo:
      #     - simple-image-deploy
      - IN: ecsProduction-deploy
      - TASK: managed 
        deployMethod: replace
        deployOptions:
          - serial
