use-shipctl-master: &masterShipctl
  - pushd /tmp
  - git clone https://github.com/trriplejay/node.git
  - ./node/shipctl/$SHIPPABLE_NODE_ARCHITECTURE/$SHIPPABLE_NODE_OPERATING_SYSTEM/install.sh
  - popd


resources:


  - name: win-repoMatchSource
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/simpleserver
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnComment: test.*
      buildOnTagPush: true
      buildOnRelease: true

  - name: win-repoMatchTarget
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/simpleserver
      tags:
        only:
          - v0.*
          - v1.*
          - v2.*
        except:
          - v0.*-test
          - v1.*-test
          - v2.*-test
      # branches:
      #   only:
      #     - master
      #     - dev*
      #   except:
      #     - dev-test
      branch: master
      buildOnCommit: false
      buildOnPullRequest: true
  - name: inparams
    type: params
    versionTemplate:
      params:
        hello: world

  - name: outparams
    type: params
    versionTemplate:
      params:
        foo: bar

jobs:


  - name: win-testStateMatching
    type: runSh
    runtime:
      nodePool: w16-byon
    steps:
      # - IN: setupJob
      - IN: win-repoMatchSource
      - IN: inparams
      - OUT: win-repoMatchTarget
      - OUT: outparams
      - TASK:
          script:
            # - *masterShipctl
            - shipctl replicate win-repoMatchSource win-repoMatchTarget -match_settings
            - shipctl replicate inparams outparams -match_settings
