resources:
  - name: hook1
    type: webhook

  - name: hook2
    type: webhook
    versionTemplate:

  - name: hook3
    type: webhook
    versionTemplate:
      test: bad
  - name: hook4
    type: webhook
    versionTemplate:
      webhookKey: "!XY"
  - name: hook5
    type: webhook
    versionTemplate:
      webhookKey: "ABCD efgh"
  - name: hook6
    type: webhook
    versionTemplate:
      webhookKey: "abcd:efgh"
  - name: hook7
    type: webhook
    versionTemplate:
      webhookKey: "f^xy!@0),,p'ew"
  - name: hook8
    type: webhook
    versionTemplate:
      webhookKey: abcd##%*&efgh
  - name: hook9
    type: webhook
    version:
      webhookKey: "noversiontemplate"
  - name: hookA
    type: webhook
    version:
      test: bad
  - name: hookB
    type: webhook
    version:
      webhookKey: "test \n test"

jobs:
  - name: testHook
    type: runSh
    steps:
      - IN: hook5
      - TASK:
          script:
            - cat $HOOK5_META/version.json
            - shipctl get_resource_version_key payload | jq '.'
