resources:

  - name: badRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/badrepo

  - name: goodImg
    type: image
    versionTemplate:
      sourceName: trriplejay/simpleserver
      versionName: master.50
      

jobs:

  - name: badRun
    type: runSh
    steps:
   #   - OUT: goodImg
      - TASK:
          script:
            - echo "hello world"
            - shipctl put_resource_state goodImg sourceName "trriplejay/micro-api"
    on_success:
      script:
        - >-
          COMMENT="This is a multi-line
          comment, isn't that great?"
        - 'this line has a : in it. i hope it works!'
        - echo "$COMMENT"
