test-state-repo: &testRepo
  - echo "testing state repo"
  - ls -latr $(shipctl get_resource_meta stateRepo)
  - cat $(shipctl get_resource_meta stateRepo)/version.json | jq '.'
  - ls -latr $(shipctl get_resource_state stateRepo)
  - cat $JOB_STATE/stateRepo.env

test-state-A: &testA
  - echo "testing stateA"
  - ls -latr $(shipctl get_resource_state stateA)
  - cat $JOB_STATE/stateA.env || echo "no env file found"
  - ls -latr $(shipctl get_resource_meta stateA)
  - cat $(shipctl get_resource_meta stateA)/version.json | jq '.' || echo "no versionjson file found"
  - echo "hello world" > test.txt
  - shipctl copy_file_to_resource_state test.txt stateA
  - shipctl copy_file_to_state test.txt
  - ls -latr $(shipctl get_resource_state stateA)
  - ls -latr $(shipctl get_resource_meta stateA)
  - cat $(shipctl get_resource_meta stateA)/version.json | jq '.' || echo "no versionjson file found"
  - ls -latr $JOB_PREVIOUS_STATE

test-state-B: &testB
  - echo "testing stateB"
  - ls -latr $(shipctl get_resource_state stateB)
  - cat $(shipctl get_resource_state stateB) stateB.env || echo "no env file found"
  - cat $JOB_STATE/stateB.env || echo "no env file found"
  - shipctl put_resource_state stateB versionName "$BUILD_NUMBER"
  - cat $JOB_STATE/stateB.env || echo "no env file found"


resources:
  - name: stateA
    type: state

  - name: stateB
    type: state

  - name: stateRepo
    type: gitRepo
    integration: github
    versionTemplate:
      branch: state
      sourceName: trriplejay/sample_pipelines


jobs:
  - name: testState1
    type: runSh
    steps:
      - IN: stateRepo
        switch: off
      - IN: stateA
        switch: off
      - OUT: stateA
      - OUT: stateB
      - TASK:
          script:
            - *testRepo
            - *testA
            - *testB

  - name: testState2
    dependencyMode: strict
    type: runSh
    steps:
      - IN: stateB
      - IN: stateA
      - TASK:
          script:
            - *testA
            - *testB